// Sample listing data for the Homes for Sale aggregator

export interface Listing {
  id: string;
  address: string;
  neighborhood: string;
  neighborhoodId: string;
  price: number;
  beds: number;
  baths: number;
  sqft: number;
  propertyType: "Single Family" | "Condo" | "Townhouse" | "Multi-Family" | "Land";
  yearBuilt: number;
  description: string;
  image: string;
  features: string[];
  daysOnMarket: number;
  priceChange: number; // negative = reduced
}

const IMG = [
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1595206137885-9ed3b46d87f8?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1575517111478-7f6afc0979db?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1583608205776-bfd35f0d9c59?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600073240990-08f66b7f59b1?w=800&q=80&auto=format&fit=crop",
];

export const LISTINGS: Listing[] = [
  {
    id: "avl-001",
    address: "42 Haywood Road",
    neighborhood: "West Asheville",
    neighborhoodId: "west-asheville",
    price: 425000,
    beds: 3,
    baths: 2,
    sqft: 1480,
    propertyType: "Single Family",
    yearBuilt: 1942,
    description: "Charming 1920s bungalow in the heart of West Asheville. Updated kitchen with quartz counters, original hardwood floors, and a screened porch overlooking a fenced backyard. Walk to Haywood Road's best cafes and breweries.",
    image: IMG[0],
    features: ["Hardwood Floors", "Updated Kitchen", "Screened Porch", "Fenced Yard", "Walk to Haywood"],
    daysOnMarket: 5,
    priceChange: 0,
  },
  {
    id: "avl-002",
    address: "215 Lexington Avenue #302",
    neighborhood: "Downtown",
    neighborhoodId: "downtown",
    price: 590000,
    beds: 2,
    baths: 2,
    sqft: 1150,
    propertyType: "Condo",
    yearBuilt: 2018,
    description: "Modern luxury condo in the heart of Downtown Asheville. Floor-to-ceiling windows with mountain views, chef's kitchen, and private balcony. Steps to 200+ restaurants, galleries, and live music venues.",
    image: IMG[1],
    features: ["Mountain Views", "Chef's Kitchen", "Balcony", "Concierge", "Parking Included"],
    daysOnMarket: 14,
    priceChange: -10000,
  },
  {
    id: "avl-003",
    address: "88 Kimberly Avenue",
    neighborhood: "North Asheville",
    neighborhoodId: "north-asheville",
    price: 785000,
    beds: 4,
    baths: 3.5,
    sqft: 2800,
    propertyType: "Single Family",
    yearBuilt: 1965,
    description: "Stately Colonial Revival on one of North Asheville's most coveted streets. Large formal living and dining rooms, updated kitchen, and a primary suite with spa bath. Mature oaks and a deep backyard — a true family home.",
    image: IMG[2],
    features: ["Colonial Revival", "Large Lot", "Spa Bath", "Formal Dining", "2-Car Garage"],
    daysOnMarket: 22,
    priceChange: 0,
  },
  {
    id: "avl-004",
    address: "310 Depot Street #105",
    neighborhood: "River Arts District",
    neighborhoodId: "river-arts",
    price: 475000,
    beds: 2,
    baths: 2,
    sqft: 1300,
    propertyType: "Condo",
    yearBuilt: 2020,
    description: "Industrial loft in a converted warehouse in the River Arts District. Exposed brick, soaring 14ft ceilings, and polished concrete floors. Walk to artist studios, breweries, and the French Broad River greenway.",
    image: IMG[3],
    features: ["Exposed Brick", "14ft Ceilings", "Concrete Floors", "Artist Studios Nearby", "River Access"],
    daysOnMarket: 8,
    priceChange: 0,
  },
  {
    id: "avl-005",
    address: "555 Vanderbilt Road",
    neighborhood: "Biltmore Forest",
    neighborhoodId: "biltmore-forest",
    price: 1395000,
    beds: 5,
    baths: 4.5,
    sqft: 4500,
    propertyType: "Single Family",
    yearBuilt: 2003,
    description: "Elegant estate in Biltmore Forest on 2.3 private acres. Grand two-story foyer, gourmet kitchen, library, wine cellar, and a resort-style pool. Adjacent to Biltmore Estate grounds. A generational property.",
    image: IMG[4],
    features: ["2.3 Acres", "Pool", "Wine Cellar", "Library", "Gated Driveway"],
    daysOnMarket: 45,
    priceChange: -50000,
  },
  {
    id: "avl-006",
    address: "178 Montford Avenue",
    neighborhood: "Montford",
    neighborhoodId: "montford",
    price: 725000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    propertyType: "Single Family",
    yearBuilt: 1910,
    description: "Meticulously restored Queen Anne Victorian in the Montford Historic District. Original gingerbread trim, stained glass windows, updated systems, and a wraparound porch. A piece of Asheville history.",
    image: IMG[5],
    features: ["Historic District", "Wraparound Porch", "Stained Glass", "Updated Systems", "Garden"],
    daysOnMarket: 10,
    priceChange: 0,
  },
  {
    id: "avl-007",
    address: "890 Hendersonville Road #45",
    neighborhood: "South Asheville",
    neighborhoodId: "south-asheville",
    price: 450000,
    beds: 3,
    baths: 2.5,
    sqft: 1950,
    propertyType: "Townhouse",
    yearBuilt: 2022,
    description: "Like-new townhome in a master-planned South Asheville community. Open floor plan, quartz counters, attached garage, and community pool. Walk to Biltmore Park Town Square. Ideal for families or professionals.",
    image: IMG[6],
    features: ["New Construction", "Community Pool", "Open Floor Plan", "Quartz Counters", "Attached Garage"],
    daysOnMarket: 18,
    priceChange: -5000,
  },
  {
    id: "avl-008",
    address: "12 Sunset Drive",
    neighborhood: "Grove Park",
    neighborhoodId: "grove-park",
    price: 895000,
    beds: 3,
    baths: 3,
    sqft: 2600,
    propertyType: "Single Family",
    yearBuilt: 1978,
    description: "Mid-century modern gem with panoramic Blue Ridge Mountain views. Floor-to-ceiling windows, exposed beams, updated kitchen and baths, and a multi-level deck. Sunsets over Mt. Pisgah every evening.",
    image: IMG[7],
    features: ["Mountain Views", "Mid-Century Modern", "Exposed Beams", "Multi-Level Deck", "Sunset Views"],
    daysOnMarket: 30,
    priceChange: 0,
  },
  {
    id: "avl-009",
    address: "5 Battery Park Avenue #702",
    neighborhood: "Downtown",
    neighborhoodId: "downtown",
    price: 675000,
    beds: 2,
    baths: 2,
    sqft: 1400,
    propertyType: "Condo",
    yearBuilt: 2019,
    description: "Penthouse-level condo in Downtown's most sought-after building. Sweeping city and mountain views from a private rooftop terrace. Designer finishes, smart home technology, and assigned parking.",
    image: IMG[0],
    features: ["Penthouse", "Rooftop Terrace", "Smart Home", "Designer Finishes", "Assigned Parking"],
    daysOnMarket: 7,
    priceChange: 0,
  },
  {
    id: "avl-010",
    address: "234 Riverview Drive",
    neighborhood: "River Arts District",
    neighborhoodId: "river-arts",
    price: 510000,
    beds: 3,
    baths: 2,
    sqft: 1650,
    propertyType: "Single Family",
    yearBuilt: 2021,
    description: "New construction modern farmhouse in the expanding RAD corridor. Open-concept living, white oak floors, and a covered back patio overlooking the French Broad River. Strong appreciation projected.",
    image: IMG[1],
    features: ["New Construction", "River Views", "White Oak Floors", "Covered Patio", "Energy Efficient"],
    daysOnMarket: 3,
    priceChange: 0,
  },
  {
    id: "avl-011",
    address: "67 Flint Street",
    neighborhood: "West Asheville",
    neighborhoodId: "west-asheville",
    price: 385000,
    beds: 2,
    baths: 1,
    sqft: 980,
    propertyType: "Single Family",
    yearBuilt: 1938,
    description: "Adorable starter bungalow on a quiet West Asheville side street. Recent updates include roof, HVAC, and kitchen. Perfect for first-time buyers or a savvy investor looking for a cosmetic flip.",
    image: IMG[2],
    features: ["Starter Home", "New Roof & HVAC", "Quiet Street", "Investment Potential", "Cosmetic Updates"],
    daysOnMarket: 2,
    priceChange: 0,
  },
  {
    id: "avl-012",
    address: "440 Caribou Road",
    neighborhood: "North Asheville",
    neighborhoodId: "north-asheville",
    price: 650000,
    beds: 3,
    baths: 2,
    sqft: 2100,
    propertyType: "Single Family",
    yearBuilt: 1955,
    description: "Mid-century ranch in North Asheville's Beaver Lake area. Original character with modern updates — new kitchen, refinished terrazzo floors, and a sunroom addition. Near UNCA and Beaver Lake Bird Sanctuary.",
    image: IMG[3],
    features: ["Near Beaver Lake", "Sunroom", "Terrazzo Floors", "Updated Kitchen", "UNCA Nearby"],
    daysOnMarket: 12,
    priceChange: 0,
  },
  {
    id: "avl-013",
    address: "14 Busbee Road #12",
    neighborhood: "South Asheville",
    neighborhoodId: "south-asheville",
    price: 340000,
    beds: 2,
    baths: 2,
    sqft: 1200,
    propertyType: "Condo",
    yearBuilt: 2016,
    description: "Well-maintained ground-floor condo in South Asheville. Open floor plan, granite counters, screened patio, and community fitness center. Great for first-time buyers or a turnkey rental investment.",
    image: IMG[4],
    features: ["Ground Floor", "Screened Patio", "Granite Counters", "Fitness Center", "Turnkey Investment"],
    daysOnMarket: 25,
    priceChange: -7500,
  },
  {
    id: "avl-014",
    address: "189 Pearson Drive",
    neighborhood: "Montford",
    neighborhoodId: "montford",
    price: 690000,
    beds: 3,
    baths: 2.5,
    sqft: 2000,
    propertyType: "Single Family",
    yearBuilt: 1925,
    description: "Arts & Crafts bungalow in the Montford Historic District with modern sensibility. Period details preserved alongside a fully renovated kitchen and baths. Walkable to downtown and Riverside Cemetery.",
    image: IMG[5],
    features: ["Arts & Crafts", "Historic District", "Renovated Kitchen", "Walk to Downtown", "Original Details"],
    daysOnMarket: 16,
    priceChange: 0,
  },
  {
    id: "avl-015",
    address: "22 Macon Avenue",
    neighborhood: "Grove Park",
    neighborhoodId: "grove-park",
    price: 1050000,
    beds: 4,
    baths: 3.5,
    sqft: 3200,
    propertyType: "Single Family",
    yearBuilt: 1995,
    description: "Stately brick home overlooking the Omni Grove Park Inn golf course. Grand living spaces, chef's kitchen, primary suite with sitting room, and a terraced garden. True Grove Park prestige.",
    image: IMG[6],
    features: ["Golf Course Views", "Chef's Kitchen", "Primary Suite", "Terraced Garden", "Brick Construction"],
    daysOnMarket: 38,
    priceChange: -25000,
  },
  {
    id: "avl-016",
    address: "401 Emma Road",
    neighborhood: "West Asheville",
    neighborhoodId: "west-asheville",
    price: 550000,
    beds: 4,
    baths: 3,
    sqft: 2200,
    propertyType: "Single Family",
    yearBuilt: 2019,
    description: "Modern craftsman with an open floor plan, chef's kitchen with gas range, and a covered front porch perfect for people-watching. Detached studio/office in back. Steps to New Belgium Brewing.",
    image: IMG[7],
    features: ["Modern Craftsman", "Detached Studio", "Gas Range", "Covered Porch", "Near Breweries"],
    daysOnMarket: 6,
    priceChange: 0,
  },
  {
    id: "avl-017",
    address: "77 Central Avenue",
    neighborhood: "Downtown",
    neighborhoodId: "downtown",
    price: 799000,
    beds: 3,
    baths: 2.5,
    sqft: 1800,
    propertyType: "Condo",
    yearBuilt: 2021,
    description: "Corner-unit luxury condo with 270-degree mountain views. Wrap-around balcony, Miele appliances, wide-plank oak floors, and two parking spaces. The most desirable address in the central business district.",
    image: IMG[0],
    features: ["Corner Unit", "Wrap-Around Balcony", "Miele Appliances", "Oak Floors", "2 Parking Spots"],
    daysOnMarket: 11,
    priceChange: 0,
  },
  {
    id: "avl-018",
    address: "333 Reed Street",
    neighborhood: "River Arts District",
    neighborhoodId: "river-arts",
    price: 420000,
    beds: 1,
    baths: 1,
    sqft: 850,
    propertyType: "Condo",
    yearBuilt: 2023,
    description: "Live/work artist loft in a brand-new RAD development. 12ft ceilings, north-facing clerestory windows for natural studio light, and a roll-up garage door that opens to a private courtyard. True creative living.",
    image: IMG[1],
    features: ["Live/Work Loft", "12ft Ceilings", "Roll-Up Door", "Clerestory Windows", "Private Courtyard"],
    daysOnMarket: 4,
    priceChange: 0,
  },
  {
    id: "avl-019",
    address: "98 Griffing Boulevard",
    neighborhood: "North Asheville",
    neighborhoodId: "north-asheville",
    price: 925000,
    beds: 5,
    baths: 4,
    sqft: 3500,
    propertyType: "Single Family",
    yearBuilt: 1928,
    description: "Restored Tudor Revival on one of North Asheville's premier streets. Original leaded glass, quarter-sawn oak floors, updated kitchen with La Cornue range, and a private garden with koi pond. Architectural significance throughout.",
    image: IMG[2],
    features: ["Tudor Revival", "Leaded Glass", "La Cornue Range", "Koi Pond", "Quarter-Sawn Oak"],
    daysOnMarket: 28,
    priceChange: -20000,
  },
  {
    id: "avl-020",
    address: "1501 Sweeten Creek Road",
    neighborhood: "South Asheville",
    neighborhoodId: "south-asheville",
    price: 520000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    propertyType: "Single Family",
    yearBuilt: 2020,
    description: "Turnkey family home in a quiet South Asheville cul-de-sac. Open main level, finished basement with media room, fenced backyard with play set. Top-rated T.C. Roberson school district. Move-in ready.",
    image: IMG[3],
    features: ["Cul-de-Sac", "Finished Basement", "Media Room", "Fenced Yard", "TC Roberson District"],
    daysOnMarket: 9,
    priceChange: 0,
  },
  {
    id: "avl-021",
    address: "45 Chestnut Street #501",
    neighborhood: "Downtown",
    neighborhoodId: "downtown",
    price: 385000,
    beds: 1,
    baths: 1,
    sqft: 720,
    propertyType: "Condo",
    yearBuilt: 2015,
    description: "Turnkey downtown pied-a-terre or STR-ready investment unit. Low HOA, strong rental history ($38K/yr gross), and walkable to everything. Sold furnished. Ideal entry point for downtown real estate investing.",
    image: IMG[4],
    features: ["STR-Ready", "Furnished", "Low HOA", "Rental History", "Walk Score 95"],
    daysOnMarket: 15,
    priceChange: 0,
  },
  {
    id: "avl-022",
    address: "612 Fairview Road",
    neighborhood: "Biltmore Forest",
    neighborhoodId: "biltmore-forest",
    price: 1650000,
    beds: 6,
    baths: 5.5,
    sqft: 5200,
    propertyType: "Single Family",
    yearBuilt: 2010,
    description: "Custom stone and timber estate on 4 private acres backing up to the Blue Ridge Parkway. Home theater, wine grotto, infinity pool, and a 3-car carriage house. The finest new construction in Biltmore Forest.",
    image: IMG[5],
    features: ["4 Acres", "Infinity Pool", "Wine Grotto", "Home Theater", "3-Car Carriage House"],
    daysOnMarket: 52,
    priceChange: -75000,
  },
  {
    id: "avl-023",
    address: "27 Craven Street",
    neighborhood: "River Arts District",
    neighborhoodId: "river-arts",
    price: 598000,
    beds: 3,
    baths: 2.5,
    sqft: 1850,
    propertyType: "Townhouse",
    yearBuilt: 2024,
    description: "Brand-new river-view townhome with rooftop deck. Open main level with 10ft ceilings, chef's kitchen with waterfall island, and a private 2-car garage. Walk to the greenway and RAD galleries. Builder warranty included.",
    image: IMG[6],
    features: ["Rooftop Deck", "River Views", "Waterfall Island", "2-Car Garage", "Builder Warranty"],
    daysOnMarket: 1,
    priceChange: 0,
  },
  {
    id: "avl-024",
    address: "119 Hillside Street",
    neighborhood: "Montford",
    neighborhoodId: "montford",
    price: 565000,
    beds: 3,
    baths: 2,
    sqft: 1700,
    propertyType: "Single Family",
    yearBuilt: 1935,
    description: "Classic Montford bungalow with a modern twist. Original heart pine floors, updated kitchen and baths, screened sleeping porch, and a landscaped lot with mature camellias. Walk to downtown in 12 minutes. A Montford gem.",
    image: IMG[7],
    features: ["Heart Pine Floors", "Screened Porch", "Mature Garden", "Walk to Downtown", "Updated Systems"],
    daysOnMarket: 13,
    priceChange: 0,
  },
  {
    id: "avl-025",
    address: "88 Brookwood Road",
    neighborhood: "Grove Park",
    neighborhoodId: "grove-park",
    price: 778000,
    beds: 3,
    baths: 2,
    sqft: 1950,
    propertyType: "Single Family",
    yearBuilt: 1962,
    description: "Renovated mid-century ranch in the coveted Grove Park neighborhood. Floor-to-ceiling windows frame Mt. Pisgah views. New kitchen, refinished terrazzo, and a sun-drenched atrium. Priced below recent comps.",
    image: IMG[0],
    features: ["Mt. Pisgah Views", "Atrium", "Terrazzo Floors", "Mid-Century", "Below Comps"],
    daysOnMarket: 5,
    priceChange: 0,
  },
];

export function getListingsByNeighborhood(neighborhoodId: string): Listing[] {
  return LISTINGS.filter((l) => l.neighborhoodId === neighborhoodId);
}

export function getListing(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}
