// Sample listing data for the Homes for Sale aggregator

export interface Listing {
  id: string;
  address: string;
  neighborhood: string;
  neighborhoodId: string;
  price: number;
  beds: number;
  baths: number;
  sqft: number;
  propertyType: "Single Family" | "Condo" | "Townhouse" | "Multi-Family" | "Land";
  yearBuilt: number;
  description: string;
  image: string;
  features: string[];
  daysOnMarket: number;
  priceChange: number; // negative = reduced
}

const PLACEHOLDER_SVG = "data:image/svg+xml;base64," + Buffer.from(
  `<svg width="600" height="400" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" style="stop-color:#0F172A"/><stop offset="100%" style="stop-color:#1E293B"/></linearGradient></defs><rect width="600" height="400" fill="url(#g)"/><rect x="80" y="180" width="180" height="140" rx="4" fill="none" stroke="rgba(16,185,129,0.15)" stroke-width="2"/><rect x="340" y="100" width="180" height="220" rx="4" fill="none" stroke="rgba(34,211,238,0.1)" stroke-width="2"/><circle cx="200" cy="400" r="160" fill="rgba(16,185,129,0.03)"/><line x1="0" y1="360" x2="600" y2="360" stroke="rgba(16,185,129,0.08)" stroke-width="2"/></svg>`
).toString("base64");

export const LISTINGS: Listing[] = [
  {
    id: "avl-001",
    address: "42 Haywood Road",
    neighborhood: "West Asheville",
    neighborhoodId: "west-asheville",
    price: 425000,
    beds: 3,
    baths: 2,
    sqft: 1480,
    propertyType: "Single Family",
    yearBuilt: 1942,
    description: "Charming 1920s bungalow in the heart of West Asheville. Updated kitchen with quartz counters, original hardwood floors, and a screened porch overlooking a fenced backyard. Walk to Haywood Road's best cafes and breweries.",
    image: PLACEHOLDER_SVG,
    features: ["Hardwood Floors", "Updated Kitchen", "Screened Porch", "Fenced Yard", "Walk to Haywood"],
    daysOnMarket: 5,
    priceChange: 0,
  },
  {
    id: "avl-002",
    address: "215 Lexington Avenue #302",
    neighborhood: "Downtown",
    neighborhoodId: "downtown",
    price: 590000,
    beds: 2,
    baths: 2,
    sqft: 1150,
    propertyType: "Condo",
    yearBuilt: 2018,
    description: "Modern luxury condo in the heart of Downtown Asheville. Floor-to-ceiling windows with mountain views, chef's kitchen, and private balcony. Steps to 200+ restaurants, galleries, and live music venues.",
    image: PLACEHOLDER_SVG,
    features: ["Mountain Views", "Chef's Kitchen", "Balcony", "Concierge", "Parking Included"],
    daysOnMarket: 14,
    priceChange: -10000,
  },
  {
    id: "avl-003",
    address: "88 Kimberly Avenue",
    neighborhood: "North Asheville",
    neighborhoodId: "north-asheville",
    price: 785000,
    beds: 4,
    baths: 3.5,
    sqft: 2800,
    propertyType: "Single Family",
    yearBuilt: 1965,
    description: "Stately Colonial Revival on one of North Asheville's most coveted streets. Large formal living and dining rooms, updated kitchen, and a primary suite with spa bath. Mature oaks and a deep backyard — a true family home.",
    image: PLACEHOLDER_SVG,
    features: ["Colonial Revival", "Large Lot", "Spa Bath", "Formal Dining", "2-Car Garage"],
    daysOnMarket: 22,
    priceChange: 0,
  },
  {
    id: "avl-004",
    address: "310 Depot Street #105",
    neighborhood: "River Arts District",
    neighborhoodId: "river-arts",
    price: 475000,
    beds: 2,
    baths: 2,
    sqft: 1300,
    propertyType: "Condo",
    yearBuilt: 2020,
    description: "Industrial loft in a converted warehouse in the River Arts District. Exposed brick, soaring 14ft ceilings, and polished concrete floors. Walk to artist studios, breweries, and the French Broad River greenway.",
    image: PLACEHOLDER_SVG,
    features: ["Exposed Brick", "14ft Ceilings", "Concrete Floors", "Artist Studios Nearby", "River Access"],
    daysOnMarket: 8,
    priceChange: 0,
  },
  {
    id: "avl-005",
    address: "555 Vanderbilt Road",
    neighborhood: "Biltmore Forest",
    neighborhoodId: "biltmore-forest",
    price: 1395000,
    beds: 5,
    baths: 4.5,
    sqft: 4500,
    propertyType: "Single Family",
    yearBuilt: 2003,
    description: "Elegant estate in Biltmore Forest on 2.3 private acres. Grand two-story foyer, gourmet kitchen, library, wine cellar, and a resort-style pool. Adjacent to Biltmore Estate grounds. A generational property.",
    image: PLACEHOLDER_SVG,
    features: ["2.3 Acres", "Pool", "Wine Cellar", "Library", "Gated Driveway"],
    daysOnMarket: 45,
    priceChange: -50000,
  },
  {
    id: "avl-006",
    address: "178 Montford Avenue",
    neighborhood: "Montford",
    neighborhoodId: "montford",
    price: 725000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    propertyType: "Single Family",
    yearBuilt: 1910,
    description: "Meticulously restored Queen Anne Victorian in the Montford Historic District. Original gingerbread trim, stained glass windows, updated systems, and a wraparound porch. A piece of Asheville history.",
    image: PLACEHOLDER_SVG,
    features: ["Historic District", "Wraparound Porch", "Stained Glass", "Updated Systems", "Garden"],
    daysOnMarket: 10,
    priceChange: 0,
  },
  {
    id: "avl-007",
    address: "890 Hendersonville Road #45",
    neighborhood: "South Asheville",
    neighborhoodId: "south-asheville",
    price: 450000,
    beds: 3,
    baths: 2.5,
    sqft: 1950,
    propertyType: "Townhouse",
    yearBuilt: 2022,
    description: "Like-new townhome in a master-planned South Asheville community. Open floor plan, quartz counters, attached garage, and community pool. Walk to Biltmore Park Town Square. Ideal for families or professionals.",
    image: PLACEHOLDER_SVG,
    features: ["New Construction", "Community Pool", "Open Floor Plan", "Quartz Counters", "Attached Garage"],
    daysOnMarket: 18,
    priceChange: -5000,
  },
  {
    id: "avl-008",
    address: "12 Sunset Drive",
    neighborhood: "Grove Park",
    neighborhoodId: "grove-park",
    price: 895000,
    beds: 3,
    baths: 3,
    sqft: 2600,
    propertyType: "Single Family",
    yearBuilt: 1978,
    description: "Mid-century modern gem with panoramic Blue Ridge Mountain views. Floor-to-ceiling windows, exposed beams, updated kitchen and baths, and a multi-level deck. Sunsets over Mt. Pisgah every evening.",
    image: PLACEHOLDER_SVG,
    features: ["Mountain Views", "Mid-Century Modern", "Exposed Beams", "Multi-Level Deck", "Sunset Views"],
    daysOnMarket: 30,
    priceChange: 0,
  },
  {
    id: "avl-009",
    address: "5 Battery Park Avenue #702",
    neighborhood: "Downtown",
    neighborhoodId: "downtown",
    price: 675000,
    beds: 2,
    baths: 2,
    sqft: 1400,
    propertyType: "Condo",
    yearBuilt: 2019,
    description: "Penthouse-level condo in Downtown's most sought-after building. Sweeping city and mountain views from a private rooftop terrace. Designer finishes, smart home technology, and assigned parking.",
    image: PLACEHOLDER_SVG,
    features: ["Penthouse", "Rooftop Terrace", "Smart Home", "Designer Finishes", "Assigned Parking"],
    daysOnMarket: 7,
    priceChange: 0,
  },
  {
    id: "avl-010",
    address: "234 Riverview Drive",
    neighborhood: "River Arts District",
    neighborhoodId: "river-arts",
    price: 510000,
    beds: 3,
    baths: 2,
    sqft: 1650,
    propertyType: "Single Family",
    yearBuilt: 2021,
    description: "New construction modern farmhouse in the expanding RAD corridor. Open-concept living, white oak floors, and a covered back patio overlooking the French Broad River. Strong appreciation projected.",
    image: PLACEHOLDER_SVG,
    features: ["New Construction", "River Views", "White Oak Floors", "Covered Patio", "Energy Efficient"],
    daysOnMarket: 3,
    priceChange: 0,
  },
  {
    id: "avl-011",
    address: "67 Flint Street",
    neighborhood: "West Asheville",
    neighborhoodId: "west-asheville",
    price: 385000,
    beds: 2,
    baths: 1,
    sqft: 980,
    propertyType: "Single Family",
    yearBuilt: 1938,
    description: "Adorable starter bungalow on a quiet West Asheville side street. Recent updates include roof, HVAC, and kitchen. Perfect for first-time buyers or a savvy investor looking for a cosmetic flip.",
    image: PLACEHOLDER_SVG,
    features: ["Starter Home", "New Roof & HVAC", "Quiet Street", "Investment Potential", "Cosmetic Updates"],
    daysOnMarket: 2,
    priceChange: 0,
  },
  {
    id: "avl-012",
    address: "440 Caribou Road",
    neighborhood: "North Asheville",
    neighborhoodId: "north-asheville",
    price: 650000,
    beds: 3,
    baths: 2,
    sqft: 2100,
    propertyType: "Single Family",
    yearBuilt: 1955,
    description: "Mid-century ranch in North Asheville's Beaver Lake area. Original character with modern updates — new kitchen, refinished terrazzo floors, and a sunroom addition. Near UNCA and Beaver Lake Bird Sanctuary.",
    image: PLACEHOLDER_SVG,
    features: ["Near Beaver Lake", "Sunroom", "Terrazzo Floors", "Updated Kitchen", "UNCA Nearby"],
    daysOnMarket: 12,
    priceChange: 0,
  },
  {
    id: "avl-013",
    address: "14 Busbee Road #12",
    neighborhood: "South Asheville",
    neighborhoodId: "south-asheville",
    price: 340000,
    beds: 2,
    baths: 2,
    sqft: 1200,
    propertyType: "Condo",
    yearBuilt: 2016,
    description: "Well-maintained ground-floor condo in South Asheville. Open floor plan, granite counters, screened patio, and community fitness center. Great for first-time buyers or a turnkey rental investment.",
    image: PLACEHOLDER_SVG,
    features: ["Ground Floor", "Screened Patio", "Granite Counters", "Fitness Center", "Turnkey Investment"],
    daysOnMarket: 25,
    priceChange: -7500,
  },
  {
    id: "avl-014",
    address: "189 Pearson Drive",
    neighborhood: "Montford",
    neighborhoodId: "montford",
    price: 690000,
    beds: 3,
    baths: 2.5,
    sqft: 2000,
    propertyType: "Single Family",
    yearBuilt: 1925,
    description: "Arts & Crafts bungalow in the Montford Historic District with modern sensibility. Period details preserved alongside a fully renovated kitchen and baths. Walkable to downtown and Riverside Cemetery.",
    image: PLACEHOLDER_SVG,
    features: ["Arts & Crafts", "Historic District", "Renovated Kitchen", "Walk to Downtown", "Original Details"],
    daysOnMarket: 16,
    priceChange: 0,
  },
  {
    id: "avl-015",
    address: "22 Macon Avenue",
    neighborhood: "Grove Park",
    neighborhoodId: "grove-park",
    price: 1050000,
    beds: 4,
    baths: 3.5,
    sqft: 3200,
    propertyType: "Single Family",
    yearBuilt: 1995,
    description: "Stately brick home overlooking the Omni Grove Park Inn golf course. Grand living spaces, chef's kitchen, primary suite with sitting room, and a terraced garden. True Grove Park prestige.",
    image: PLACEHOLDER_SVG,
    features: ["Golf Course Views", "Chef's Kitchen", "Primary Suite", "Terraced Garden", "Brick Construction"],
    daysOnMarket: 38,
    priceChange: -25000,
  },
];

export function getListingsByNeighborhood(neighborhoodId: string): Listing[] {
  return LISTINGS.filter((l) => l.neighborhoodId === neighborhoodId);
}

export function getListing(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}
