/**
 * Buncombe County terrain metadata — generated by scripts/bake-terrain.mjs.
 * Heightmap: public/terrain/buncombe-heightmap.png (16-bit, R=high byte, G=low byte).
 * Source: USGS 3DEP 1 arc-second DEM (public domain). Elevation in meters.
 */
export const TERRAIN = {
  size: 256,
  bounds: { west: -82.9, south: 35.2, east: -82, north: 35.9 },
  minElevationM: 219.5,
  maxElevationM: 2014.7,
} as const;

export type TerrainBounds = (typeof TERRAIN)["bounds"];
