/**
 * Terrain bake — AshevilleRE
 * --------------------------
 * Downloads USGS 3DEP 1 arc-second DEM tiles (public domain, no API key),
 * crops to Buncombe County bounds, normalizes elevation to a 16-bit
 * heightmap PNG at public/terrain/buncombe-heightmap.png.
 *
 * Buncombe County sits entirely within 1°×1° tiles n36w082 + n36w083
 * (confirmed via TNM API: bbox -82.9,35.2,-82.0,35.9).
 *
 * Run:  node scripts/bake-terrain.mjs
 * Refs: https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1/TIFF/historical/
 */

import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { fromArrayBuffer } from "geotiff";
import { PNG } from "pngjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Buncombe County, NC bounding box (lon/lat).
const BOUNDS = { west: -82.9, south: 35.2, east: -82.0, north: 35.9 };
const SIZE = 256;

// Buncombe County, NC sits in 1°×1° tile n36w083 (lon -83..-82, lat 35..36).
// Confirmed via TNM API + direct georeference: bbox [-83.0017, 34.9983, -81.9983, 36.0017].
const TILES = [
  {
    url: "https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1/TIFF/historical/n36w083/USGS_1_n36w083_20220504.tif",
    col: 0,
  },
];

async function download(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function tileGeoTiff(url) {
  const buf = await download(url);
  return fromArrayBuffer(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
}

async function main() {
  const dem = new Float32Array(SIZE * SIZE);
  let have = 0;

  for (const { url } of TILES) {
    console.log(`Fetching ${url}`);
    const tiff = await tileGeoTiff(url);
    const image = await tiff.getImage();
    const [w, h] = [image.getWidth(), image.getHeight()];
    const [originLon, originLat] = image.getOrigin();
    const [dx, dy] = image.getResolution();
    const data = await image.readRasters({ interleave: true });
    console.log(`  ${w}×${h}, origin ${originLon},${originLat}, dx ${dx} dy ${dy}`);

    for (let iy = 0; iy < SIZE; iy++) {
      for (let ix = 0; ix < SIZE; ix++) {
        const lon = BOUNDS.west + (ix / (SIZE - 1)) * (BOUNDS.east - BOUNDS.west);
        const lat = BOUNDS.north - (iy / (SIZE - 1)) * (BOUNDS.north - BOUNDS.south);
        const sx = Math.floor((lon - originLon) / dx);
        // North-up: origin is the north edge, rows grow south (dy negative).
        const row = Math.floor((originLat - lat) / Math.abs(dy));
        if (sx < 0 || row < 0 || sx >= w || row >= h) continue;
        const v = data[row * w + sx];
        if (typeof v === "number" && Number.isFinite(v)) {
          dem[iy * SIZE + ix] = v;
          have++;
        }
      }
    }
  }

  console.log(`Sampled ${have}/${SIZE * SIZE} cells`);

  // Fill any gaps with the nearest valid sample (seams).
  for (let pass = 0; pass < 3; pass++) {
    let filled = 0;
    for (let i = 0; i < SIZE * SIZE; i++) {
      if (Number.isFinite(dem[i])) continue;
      const x = i % SIZE;
      const y = (i / SIZE) | 0;
      let acc = 0;
      let n = 0;
      for (let dy = -1; dy <= 1; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          const j = (y + dy) * SIZE + (x + dx);
          if (j < 0 || j >= SIZE * SIZE) continue;
          if (Number.isFinite(dem[j])) {
            acc += dem[j];
            n++;
          }
        }
      }
      if (n) {
        dem[i] = acc / n;
        filled++;
      }
    }
    console.log(`  pass ${pass + 1}: filled ${filled}`);
    if (!filled) break;
  }

  let min = Infinity;
  let max = -Infinity;
  let ok = 0;
  for (const v of dem) {
    if (Number.isFinite(v)) {
      if (v < min) min = v;
      if (v > max) max = v;
      ok++;
    }
  }
  if (ok < SIZE * SIZE * 0.5) throw new Error(`Too few valid samples: ${ok}`);
  console.log(`Elevation range: ${min.toFixed(1)}m – ${max.toFixed(1)}m (${ok} cells)`);

  const png = new PNG({ width: SIZE, height: SIZE });
  for (let i = 0; i < SIZE * SIZE; i++) {
    const v = Number.isFinite(dem[i]) ? dem[i] : min;
    const n = Math.round(((v - min) / (max - min)) * 65535);
    const hi = (n >> 8) & 0xff;
    const lo = n & 0xff;
    png.data[i * 4] = hi;
    png.data[i * 4 + 1] = lo;
    png.data[i * 4 + 2] = 0;
    png.data[i * 4 + 3] = 255;
  }

  await mkdir(join(ROOT, "public", "terrain"), { recursive: true });
  const out = join(ROOT, "public", "terrain", "buncombe-heightmap.png");
  await writeFile(out, PNG.sync.write(png));
  console.log(`Wrote ${out}`);

  const meta = `/**
 * Buncombe County terrain metadata — generated by scripts/bake-terrain.mjs.
 * Heightmap: public/terrain/buncombe-heightmap.png (16-bit, R=high byte, G=low byte).
 * Source: USGS 3DEP 1 arc-second DEM (public domain). Elevation in meters.
 */
export const TERRAIN = {
  size: ${SIZE},
  bounds: { west: ${BOUNDS.west}, south: ${BOUNDS.south}, east: ${BOUNDS.east}, north: ${BOUNDS.north} },
  minElevationM: ${min.toFixed(1)},
  maxElevationM: ${max.toFixed(1)},
} as const;

export type TerrainBounds = (typeof TERRAIN)["bounds"];
`;
  await writeFile(join(ROOT, "lib", "terrain.ts"), meta);
  console.log("Wrote lib/terrain.ts");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
